# Generated by Django 5.1.1 on 2025-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="numero_client",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
