# Generated by Django 5.1.1 on 2025-04-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoice_facture_liee_alter_invoice_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="facture_liee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs_lies",
                to="billing.invoice",
            ),
        ),
    ]
