# Generated by Django 5.1.1 on 2025-04-26 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_invoice_facture_liee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="facture_liee",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("R", "RECEIPT"), ("P", "PROFORMA INVOICE"), ("I", "INVOICE")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Avoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avoir_date_time", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="avoirs/logos/"),
                ),
                ("numero_avoir", models.PositiveIntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs",
                        to="billing.invoice",
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("save_by", "numero_avoir"), name="unique_avoir_per_user"
                    )
                ],
                "unique_together": {("save_by", "numero_avoir")},
            },
        ),
    ]
