# Generated by Django 5.1.1 on 2025-04-06 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="verification_expires",
            field=models.DateField(default=datetime.date(2025, 4, 9)),
        ),
    ]
