# Generated by Django 5.1.1 on 2025-04-02 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="verification_expires",
            field=models.DateField(default=datetime.date(2025, 4, 5)),
        ),
        migrations.DeleteModel(
            name="PayHistory",
        ),
    ]
